import { Metadata } from 'next'
import './globals.css'
import TheHeader from '@/components/TheHeader'
import TheFooter from '@/components/TheFooter'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="container mx-auto flex flex-col min-h-screen">
        <TheHeader />
        {children}
        <TheFooter />
      </body>
    </html>
  )
}
