import './globals.css'
import TheHeader from '@/components/UI/TheHeader'
import TheFooter from '@/components/UI/TheFooter'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto flex flex-col min-h-screen">
        <TheHeader />
        {children}
        <TheFooter />
      </body>
    </html>
  )
}
