# Generated by Django 4.2.1 on 2023-06-10 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=258, verbose_name="token")),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, verbose_name="amount"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date of creation"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="from_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="from user",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="to_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="to user",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
            },
        ),
        migrations.CreateModel(
            name="PublicNFT",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=258,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.models.upload_to, verbose_name="image"
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, verbose_name="amount"),
                ),
                (
                    "date_of_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date of creation"
                    ),
                ),
                (
                    "date_of_change",
                    models.DateTimeField(auto_now=True, verbose_name="date of change"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "public NFT",
                "verbose_name_plural": "public NFTs",
            },
        ),
    ]
