# Generated by Django 4.2.1 on 2023-06-15 09:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicNFT",
            fields=[
                (
                    "token_id",
                    models.IntegerField(
                        max_length=258,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="token id",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.models.upload_to, verbose_name="image"
                    ),
                ),
            ],
            options={
                "verbose_name": "public NFT",
                "verbose_name_plural": "public NFTs",
            },
        ),
    ]
