# Generated by Django 4.2.1 on 2023-06-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicnft",
            name="token_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, unique=True, verbose_name="token id"
            ),
        ),
    ]
