# Generated by Django 4.2.1 on 2023-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicnft",
            name="id",
        ),
        migrations.AlterField(
            model_name="publicnft",
            name="token",
            field=models.CharField(
                max_length=258,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="token",
            ),
        ),
    ]
